pipeline
{
    agent any
    stages{
        stage ('Create Image'){
            steps{
                script{
                   dockerapp = docker.build("deivisson/kube-news:${env.BUILD_ID}", '-f ./src/Dockerfile ./src')     
                }
            }
        }
    }
}